apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: hydrate-dashboard
profiles:
  - name: prod
    build:
      artifacts:
        - image: gfacratharipazwe.azurecr.io/frontend/aquametrics/website:latest
          docker:
            dockerfile: Dockerfile
    manifests:
      kustomize:
        paths:
          - ./manifest/prod
