apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: aqm-prod-hydrate-net
  namespace: istio-system
spec:
  secretName: aqm-prod-hydrate-net-tls
  issuerRef:
    name: letsencrypt
  commonName: preview.aquametrics.ch
  dnsNames:
    - preview.aquametrics.ch
