# .github/workflows/angular-cd.yml

name: Angular CI/CD with Digital Ocean

on:
  push:
    branches:
      - main # Change this to the branch you want to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x' # Change this to match your project's Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build Angular app
      run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Displaying Current Directory
        run: ls -a 
      - name: Display Contents of "dist" Directory
        run: ls -lR dist
      - name: Deploy to Digital Ocean
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist"
          target: /var/www/html/

